### ISSUE TITLE
Amazing repo! But it seems cannot run~

### ISSUE THREAD

**Issue by shaunhurryup** [omarelshopky/DarkSnakeCubeSolverRobot#1]
When I clone the repo and install some requirements such as `opencv-python` `scipy` `IPython`，and run `python3 GUI.py`, an error happened.

```sh
> python3 GUI.py

Traceback (most recent call last):
  File "/Users/xxx/Desktop/xxx/DarkSnakeCubeSolverRobot/GUI.py", line 28, in <module>
    import colors_recognition as cam        # recognize cube status via a webcam (by Andrea Favero)
  File "/Users/xxx/Desktop/xxx/DarkSnakeCubeSolverRobot/colors_recognition.py", line 32, in <module>
    import twophase.solver as sv                                 # Kociemba solver
ModuleNotFoundError: No module named 'twophase.solver'
```

Looking forward to receiving your early reply, thanks!!!

**Comment by omarelshopky** [comment]
It would be best to use pipenv package manager to install all dependencies in the Pipfile or install each of them manually.

If you face any problems, ping me!
